apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: getting-started
stringData:
  token: "NWRkZWQ0M2IyMDI1NjYxZmI5MGVjOWNjMmIzYmVmNThlZTNlYWE3NQ=="
  secret: "YmhhdmlzaGthCg=="